### PR TITLE
Broken down the get_bridge_openings function

### LINKED ISSUE #155: Put redundant code for downloading XML into a function
We probably need a new function (`get_xml` ?) that performs these actions

1. Downloading a .gz file containing an XML file

1. Unzipping the .gz file 

1. Converting the XML file to an XML document.

1. Return the XML document.

`get_bridge_openings` and `get_car_densities` now contain redundant code doing this.

### LINKED ISSUE #161: Break down the get_bridge_openings function
At the moment, the get_bridge_openings function does many things.

Break the function into two blocks:

1. get the data from the internet and place it into an xml object
2. extract the desired data from the xml object (leave this with the name get_bridge_openings)

### PR DESCRIPTION
**Pull request by janclod**
Closes: #155, #161

Opens: #163

### CODE REVIEW

File: tests/testthat/test-get_bridge_openings.R [hunk 1]
```diff
@@ -21,12 +21,26 @@ if (nrow(bridges) > 0) {
 
 }
 
-test_that("no NA data", {
+# Using the mockery package to test functions on fake data
+# Mock data
+fake_xml_bridges <- mock(xml2::read_xml("./test_dataset/bridges.xml"),
```
Comment (FrieseWoudloper) [inline tests/testthat/test-get_bridge_openings.R:26]: Nice!

**Review by FrieseWoudloper — APPROVED** [review]

File: tests/testthat/test-get_bridge_openings.R (hunk 1 above)
Comment (richelbilderbeek) [reply tests/testthat/test-get_bridge_openings.R:26]: Awesome!
